"""Reverse Wordle solver: reconstruct the most likely guess sequence from a pattern trace.

Given the correct answer and the color pattern for each row, this module finds the
most probable sequence of guesses a human player made, using a Boltzmann model of
rationality calibrated against the entropy-based forward solver.
"""

from __future__ import annotations

import json
import logging
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from scipy.special import log_softmax

from src.entropy import get_entropies
from src.pattern import get_pattern_matrix, get_possible_words, pattern_to_int_list, pattern_to_string
from src.prior import get_true_wordle_prior, get_word_list
from src.solver import get_weights

logger = logging.getLogger(__name__)

# Rationality presets: higher beta = closer to optimal play
BETA_PRESETS: dict[str, float] = {
    "random": 0.0,
    "casual": 2.0,
    "normal": 5.0,
    "expert": 10.0,
}

# Precomputed forward-solver prior for first guesses.
# Maps word -> log_prior (0.0 = best opener, more negative = worse).
# Generated by precompute_opener_prior.py; covers the 2,315 answer words.
# Words not in the dict (non-answer words) contribute 0 here; they are handled
# by the out-of-list discount instead.
_OPENER_PRIOR_FILE = Path(__file__).parent.parent / "data" / "wordle" / "opener_prior.json"
OPENER_PRIOR: dict[str, float] = {}
OPENER_PRIOR_WEIGHT: float = 10.0   # step 0 (opener selection)
WORD_QUALITY_WEIGHT: float = 3.0    # steps 1+ (familiarity proxy)
POSSIBLE_ANSWER_BONUS: float = 3.5       # nats bonus at n=1 remaining (endgame)
POSSIBLE_ANSWER_BONUS_BASE: float = 1.0  # nats bonus at n>=ANSWER_BONUS_RAMP_N remaining
ANSWER_BONUS_RAMP_N: int = 12            # linearly interpolate between base and full below this

# Multiplicative prior applied to words outside the official answer list, both as
# guess choices and (for the actual answer, post-2022 NYT answers etc.) as the
# possible-answer prior. 0.1 = an out-of-list word is 10x less likely a priori.
OUT_OF_LIST_DISCOUNT: float = 0.1

# Non-answer words are always considered at step 0 (a single beam state, and the
# step where enthusiast openers like SOARE appear) and at any later step where
# fewer than this many answer-list words match the observed pattern. When
# answer-list matches are plentiful, scoring only those keeps the beam-search
# cost bounded; the discount would bury out-of-list words there anyway.
NON_ANSWER_UNION_THRESHOLD: int = 60

# Wordle allows at most 6 guesses
MAX_GUESSES: int = 6

try:
    OPENER_PRIOR = json.loads(_OPENER_PRIOR_FILE.read_text())
except FileNotFoundError:
    logging.getLogger(__name__).warning(
        "opener_prior.json not found — run precompute_opener_prior.py to generate it. "
        "First-guess prior will be flat."
    )

ALL_GREEN_PATTERN: int = 3**5 - 1  # 242

_EMOJI_TO_INT = {"⬛": 0, "⬜": 0, "🟨": 1, "🟩": 2}
# Decoration codepoints that platforms may inject next to emoji tiles
_IGNORED_CHARS = {"\ufe0f", "\u200d"}  # variation selector-16, zero-width joiner


# ---------------------------------------------------------------------------
# Pattern parsing
# ---------------------------------------------------------------------------


def parse_pattern(pattern) -> int:
    """Convert a pattern to its integer encoding (0–242).

    Accepts:
    - An int already in range 0–242
    - A 5-element list/tuple of ints in {0, 1, 2}  (MISS=0, MISPLACED=1, EXACT=2)
    - A 5-emoji string using ⬛/⬜, 🟨, 🟩 (variation selectors are ignored)
    """
    if isinstance(pattern, int):
        if not 0 <= pattern <= 242:
            raise ValueError(f"Pattern int must be 0–242, got {pattern}")
        return pattern
    if isinstance(pattern, str):
        chars = [c for c in pattern if c not in _IGNORED_CHARS]
        if len(chars) != 5 or not all(c in _EMOJI_TO_INT for c in chars):
            raise ValueError(
                f"Pattern string must be 5 emoji from {{⬛,⬜,🟨,🟩}}, got '{pattern}'"
            )
        return sum(_EMOJI_TO_INT[c] * (3**i) for i, c in enumerate(chars))
    values = list(pattern)
    if len(values) != 5:
        raise ValueError(f"Pattern list must have length 5, got {len(values)}")
    if not all(v in (0, 1, 2) for v in values):
        raise ValueError(f"Pattern values must be in {{0,1,2}}, got {values}")
    return sum(int(v) * (3**i) for i, v in enumerate(values))


def parse_pattern_trace(patterns: list) -> list[int]:
    """Normalize a full trace.

    A winning trace ends with the all-green row (242). A losing trace — the
    player ran out of guesses — is also accepted: it must have exactly
    MAX_GUESSES rows and contain no all-green row. No pattern before the last
    row may be all-green (the game would already have ended there).
    """
    parsed = [parse_pattern(p) for p in patterns]
    if not parsed:
        raise ValueError("Pattern trace must be non-empty")
    for i, p in enumerate(parsed[:-1]):
        if p == ALL_GREEN_PATTERN:
            raise ValueError(
                f"Pattern {i + 1} is all-green but is not the last row — "
                "the game would have ended there."
            )
    if parsed[-1] != ALL_GREEN_PATTERN and len(parsed) != MAX_GUESSES:
        raise ValueError(
            f"Last pattern must be all-green ({ALL_GREEN_PATTERN}) for a won game, "
            f"and a lost game must show all {MAX_GUESSES} rows (got {len(parsed)})."
        )
    return parsed


def parse_share_text(text: str) -> list[int]:
    """Extract the pattern trace from a pasted Wordle share block.

    Accepts the full clipboard format:
        Wordle 1,784 4/6

        🟨🟨⬛⬛⬛
        🟨⬛⬛🟨🟨
        ...

    Rules:
    - Lines with no tile emoji (headers, blank lines, comments) are skipped.
    - Decorations are tolerated: variation selectors / zero-width joiners are
      stripped, and non-tile characters (e.g. 😂 appended to a row) are ignored.
    - A line that DOES contain tile emoji must contain exactly 5 of them —
      a malformed tile row raises instead of being silently dropped, so a
      corrupted paste can never reconstruct the wrong game.
    - Both ⬛ (black) and ⬜ (white) count as gray/miss.
    """
    rows: list[int] = []
    for line in text.splitlines():
        cleaned = "".join(c for c in line if c not in _IGNORED_CHARS)
        tiles = [c for c in cleaned if c in _EMOJI_TO_INT]
        if not tiles:
            continue
        if len(tiles) != 5:
            raise ValueError(
                f"Tile row {len(rows) + 1} has {len(tiles)} tiles instead of 5: "
                f"'{line.strip()}'. Fix the row or remove it."
            )
        rows.append(parse_pattern("".join(tiles)))
    if not rows:
        raise ValueError(
            "No emoji rows found. Paste the full Wordle share including the emoji grid."
        )
    if len(rows) > MAX_GUESSES:
        raise ValueError(f"Found {len(rows)} tile rows; Wordle allows at most {MAX_GUESSES}.")
    return parse_pattern_trace(rows)


# ---------------------------------------------------------------------------
# Candidate lookup
# ---------------------------------------------------------------------------


def get_candidates_for_pattern(
    answer: str,
    pattern: int,
    allowed_words: list[str],
    game_name: str,
) -> list[str]:
    """Return every word in allowed_words that produces `pattern` against `answer`."""
    col = get_pattern_matrix(allowed_words, [answer], game_name).flatten()
    return [w for w, p in zip(allowed_words, col) if p == pattern]


# ---------------------------------------------------------------------------
# Hard mode
# ---------------------------------------------------------------------------


def merge_hard_mode_constraints(
    guesses: list[str],
    patterns: list[int],
) -> tuple[dict[int, str], dict[str, int]]:
    """Merge the hint history into a single hard-mode constraint.

    Returns (fixed, min_counts): green letters that must stay in position, and
    the minimum number of copies of each hinted letter the next guess must
    contain (greens + yellows per guess, maximized across guesses).

    Note: real Wordle hard mode does NOT forbid reusing gray letters, and does
    not require avoiding a yellow letter's previous position — only that
    revealed hints are used.
    """
    fixed: dict[int, str] = {}
    min_counts: dict[str, int] = {}
    for guess, pattern in zip(guesses, patterns):
        ints = pattern_to_int_list(pattern)
        counts: dict[str, int] = {}
        for i, (ch, v) in enumerate(zip(guess, ints)):
            if v == 2:
                fixed[i] = ch
                counts[ch] = counts.get(ch, 0) + 1
            elif v == 1:
                counts[ch] = counts.get(ch, 0) + 1
        for ch, n in counts.items():
            if n > min_counts.get(ch, 0):
                min_counts[ch] = n
    return fixed, min_counts


def satisfies_hard_mode(word: str, fixed: dict[int, str], min_counts: dict[str, int]) -> bool:
    """True if `word` is a legal hard-mode guess under the merged constraints."""
    for i, ch in fixed.items():
        if word[i] != ch:
            return False
    for ch, n in min_counts.items():
        if word.count(ch) < n:
            return False
    return True


# ---------------------------------------------------------------------------
# Beam search state
# ---------------------------------------------------------------------------


@dataclass
class BeamState:
    guesses: list[str] = field(default_factory=list)
    remaining_words: list[str] = field(default_factory=list)
    log_prob: float = 0.0
    step_probs: list[float] = field(default_factory=list)
    # (n_remaining_before, n_remaining_after) at each step
    remaining_sizes: list[tuple[int, int]] = field(default_factory=list)
    # number of candidate guesses this state actually chose among, per step
    n_candidates: list[int] = field(default_factory=list)
    # top alternatives (word, prob) at each step
    top_alternatives_per_step: list[list[tuple[str, float]]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------


def _score_candidates(
    candidates: list[str],
    entropies: np.ndarray,
    remaining_set: set[str],
    n_remaining: int,
    beta: float,
    step: int,
    answer_list_set: set[str],
    out_of_list_discount: float,
    use_opener_prior: bool,
) -> np.ndarray:
    """Return log-probabilities for the human choosing each candidate.

    Model: P(G | state) ∝ exp(β·H(G) + prior terms), where H(G) is the Shannon
    entropy gained by guessing G given the current remaining word distribution.
    Prior terms: a forward-solver word-quality prior (openers weighted highest),
    a possible-answer bonus that ramps up in the endgame, and a log-discount for
    words outside the official answer list.
    """
    scores = beta * entropies

    # Possible-answer bonus: linearly ramps from POSSIBLE_ANSWER_BONUS (at n=1)
    # down to POSSIBLE_ANSWER_BONUS_BASE (at n>=ANSWER_BONUS_RAMP_N).
    # Models (a) lucky-win probability and (b) human preference for real words.
    t = max(0.0, min(1.0, (ANSWER_BONUS_RAMP_N - n_remaining) / (ANSWER_BONUS_RAMP_N - 1)))
    answer_bonus = POSSIBLE_ANSWER_BONUS_BASE + (POSSIBLE_ANSWER_BONUS - POSSIBLE_ANSWER_BONUS_BASE) * t
    scores = scores + answer_bonus * np.array(
        [1.0 if c in remaining_set else 0.0 for c in candidates]
    )

    if use_opener_prior:
        # Word-quality prior at every step: better openers (via forward solver)
        # serve as a proxy for word familiarity. Weight is higher at step 0, where
        # humans rely most on prior knowledge, and lower thereafter. Words absent
        # from the dict contribute 0; the out-of-list discount below handles them.
        weight = OPENER_PRIOR_WEIGHT if step == 0 else WORD_QUALITY_WEIGHT
        scores += weight * np.array(
            [OPENER_PRIOR.get(c, 0.0) for c in candidates]
        )

    if out_of_list_discount < 1.0:
        # Soft prior against obscure-but-valid words (REALO, FUBAR, ...): a word
        # outside the official answer list is `out_of_list_discount` times less
        # likely to be chosen, all else equal.
        log_discount = math.log(out_of_list_discount)
        scores += log_discount * np.array(
            [0.0 if c in answer_list_set else 1.0 for c in candidates]
        )

    return log_softmax(scores)


# ---------------------------------------------------------------------------
# Main reconstruction function
# ---------------------------------------------------------------------------


def reconstruct_guesses(
    patterns: list,
    answer: str,
    game_name: str = "wordle",
    beta: float = 5.0,
    beam_width: int = 200,
    expansion_per_state: int = 20,
    priors: dict[str, float] | None = None,
    n_top_alternatives: int = 5,
    hard_mode: bool = False,
    restrict_to_answers: bool = False,
    out_of_list_discount: float = OUT_OF_LIST_DISCOUNT,
) -> list[dict]:
    """Reconstruct the most likely sequence of Wordle guesses from a pattern trace.

    Args:
        patterns: List of N patterns. Each can be an int (0–242), a 5-int list, or
                  a 5-emoji string. A won game ends with the all-green row; a lost
                  game is a full 6-row trace with no all-green row.
        answer:   The correct answer word. May be outside the official answer list
                  (e.g. post-2022 NYT answers): it then participates with an
                  `out_of_list_discount` prior instead of being excluded.
        game_name: "wordle" or "dungleon".
        beta:     Rationality parameter. Use BETA_PRESETS or pass a float directly.
                  0 = random play, 5 = normal human, 10 = near-optimal.
        beam_width: States kept after pruning at each step. Larger values improve the
                    probability denominator estimate and yield more merge candidates.
                    Default 200.
        expansion_per_state: Candidates expanded per beam state per step. Controls
                    compute cost independently of beam_width. Default 20.
        priors:   Word probability dict. Defaults to the official answer-list prior.
        n_top_alternatives: Alternatives to report per step in output.
        hard_mode: If True, every guess must reuse revealed hints (greens stay in
                   position, yellow/green letters must appear), matching real
                   Wordle hard-mode rules.
        restrict_to_answers: If True, only official answer-list words are considered
                             as guesses. Default False: all valid words are
                             considered, with out-of-list words discounted by
                             `out_of_list_discount` rather than excluded.
        out_of_list_discount: Multiplicative prior (0-1] for words outside the
                             official answer list, applied both to guess choice
                             and to an out-of-list answer's weight in the
                             remaining-word distribution. Default 0.1 (10x less
                             likely). 1.0 disables the discount.

    Returns:
        List of result dicts ranked by probability. Each dict contains:
          rank, guesses, won, log_probability, normalized_probability, step_info.
        step_info is a list of per-step dicts with guess, pattern, pattern_str,
        n_candidates, n_remaining_before, n_remaining_after, step_probability,
        top_alternatives. For a lost game, `won` is False and all N observed
        guesses are reconstructed (none of them is the answer).
    """
    parsed_patterns = parse_pattern_trace(patterns)
    n_guesses = len(parsed_patterns)
    won = parsed_patterns[-1] == ALL_GREEN_PATTERN
    # For a win, the final guess is deterministically the answer, so only the
    # earlier rows are searched. For a loss, every observed row is a real
    # guess to reconstruct (the "7th all-green try" is implicit: the answer is
    # given and stays consistent with every row by construction).
    n_search_steps = n_guesses - 1 if won else n_guesses

    if not 0.0 < out_of_list_discount <= 1.0:
        raise ValueError(f"out_of_list_discount must be in (0, 1], got {out_of_list_discount}")

    if priors is None:
        priors = get_true_wordle_prior(game_name)

    allowed_words = get_word_list(game_name, short=False)
    possible_words = get_word_list(game_name, short=True)
    answer_list_set = set(possible_words)

    allowed_set = set(allowed_words)
    if answer not in allowed_set:
        raise ValueError(f"Answer '{answer}' not in allowed words for game '{game_name}'")

    # If the answer is outside the prior's support (e.g. a post-2022 NYT answer
    # that isn't in the original list), give it a discounted prior instead of
    # excluding it — otherwise the possibility set the model reasons over could
    # never contain the actual answer, silently distorting probabilities or
    # collapsing the beam on perfectly consistent traces.
    priors = dict(priors)
    if priors.get(answer, 0) <= 0:
        max_prior = max(priors.values(), default=0) or 1.0
        priors[answer] = out_of_list_discount * max_prior
        logger.info(
            "Answer '%s' is outside the official answer list; "
            "including it with a %gx discounted prior.",
            answer, out_of_list_discount,
        )

    # Initial remaining: possible answers with nonzero prior (matches forward
    # solver), plus the actual answer if it's out of list.
    initial_remaining = [w for w in possible_words if priors.get(w, 0) > 0]
    if answer not in initial_remaining:
        initial_remaining.append(answer)

    # Word-quality prior only applies to the game it was computed for
    use_opener_prior = bool(OPENER_PRIOR) and game_name == "wordle"

    # Precompute candidates for each searched step (for a won game the last row
    # is always the answer, pattern 242, and is not searched). The player's
    # guesses may be any valid word: non-answer words are down-weighted in
    # scoring via `out_of_list_discount` rather than excluded. To bound compute,
    # the full vocabulary is only mixed in at step 0 and wherever answer-list
    # matches are scarce (< NON_ANSWER_UNION_THRESHOLD).
    step_candidates: list[list[str]] = []
    for k in range(n_search_steps):
        candidates = get_candidates_for_pattern(
            answer, parsed_patterns[k], possible_words, game_name
        )
        if not restrict_to_answers and (
            k == 0 or len(candidates) < NON_ANSWER_UNION_THRESHOLD
        ):
            candidates = get_candidates_for_pattern(
                answer, parsed_patterns[k], allowed_words, game_name
            )
        if not candidates:
            raise ValueError(
                f"No {'answer-list' if restrict_to_answers else 'valid'} word produces "
                f"pattern {parsed_patterns[k]} ({pattern_to_string(parsed_patterns[k])}) "
                f"against answer '{answer}' at step {k + 1}. "
                "The trace may be inconsistent with the answer."
            )
        logger.debug(
            "Step %d: %d candidates for %s",
            k + 1, len(candidates), pattern_to_string(parsed_patterns[k]),
        )
        step_candidates.append(candidates)

    # Initialize beam with a single state covering all possible answers
    beam: list[BeamState] = [BeamState(remaining_words=initial_remaining)]

    # -----------------------------------------------------------------------
    # Beam search over the observed guesses
    # -----------------------------------------------------------------------
    for k in range(n_search_steps):
        all_candidates = step_candidates[k]
        p_k = parsed_patterns[k]
        new_beam: list[BeamState] = []
        # Entropies depend only on (candidates, remaining set); many beam states
        # converge to identical remaining sets, so cache per step.
        entropy_cache: dict[tuple[str, ...], np.ndarray] = {}

        for state in beam:
            if not state.remaining_words:
                continue

            # Hard mode: the guess must honor every hint revealed so far
            cand_idx = None  # None = all of all_candidates
            if hard_mode and state.guesses:
                fixed, min_counts = merge_hard_mode_constraints(
                    state.guesses, parsed_patterns[: len(state.guesses)]
                )
                cand_idx = [
                    i for i, c in enumerate(all_candidates)
                    if satisfies_hard_mode(c, fixed, min_counts)
                ]
                if not cand_idx:
                    continue

            # Players don't repeat a guess (it reveals nothing new), so drop
            # already-guessed words — unless that would leave no candidates,
            # in which case the repeat is what the trace actually shows.
            if state.guesses:
                guessed = set(state.guesses)
                pool = cand_idx if cand_idx is not None else range(len(all_candidates))
                pool_size = len(cand_idx) if cand_idx is not None else len(all_candidates)
                no_repeat = [i for i in pool if all_candidates[i] not in guessed]
                if no_repeat and len(no_repeat) < pool_size:
                    cand_idx = no_repeat

            candidates = (
                all_candidates if cand_idx is None
                else [all_candidates[i] for i in cand_idx]
            )

            remaining_key = tuple(state.remaining_words)
            all_entropies = entropy_cache.get(remaining_key)
            if all_entropies is None:
                weights = get_weights(state.remaining_words, priors)
                all_entropies = get_entropies(
                    all_candidates, state.remaining_words, weights, game_name
                )
                entropy_cache[remaining_key] = all_entropies
            entropies = all_entropies if cand_idx is None else all_entropies[cand_idx]

            log_probs = _score_candidates(
                candidates,
                entropies,
                set(state.remaining_words),
                len(state.remaining_words),
                beta,
                step=k,
                answer_list_set=answer_list_set,
                out_of_list_discount=out_of_list_discount,
                use_opener_prior=use_opener_prior,
            )

            order = np.argsort(log_probs)

            # Top alternatives for output (before expansion pruning)
            top_alt_idx = order[-n_top_alternatives:][::-1]
            top_alts = [
                (candidates[i], float(np.exp(log_probs[i]))) for i in top_alt_idx
            ]

            # Expand top candidates per state; keep beam_width separate from expansion
            # so the stored beam is large (good denominator) without quadratic blowup.
            expansion_limit = min(expansion_per_state, len(candidates))
            expand_idx = order[-expansion_limit:]

            n_before = len(state.remaining_words)
            for i in expand_idx:
                guess = candidates[i]
                lp = float(log_probs[i])
                new_remaining = get_possible_words(
                    guess, p_k, state.remaining_words, game_name
                )
                new_beam.append(BeamState(
                    guesses=state.guesses + [guess],
                    remaining_words=new_remaining,
                    log_prob=state.log_prob + lp,
                    step_probs=state.step_probs + [float(np.exp(lp))],
                    remaining_sizes=state.remaining_sizes + [(n_before, len(new_remaining))],
                    n_candidates=state.n_candidates + [len(candidates)],
                    top_alternatives_per_step=state.top_alternatives_per_step + [top_alts],
                ))

        if not new_beam:
            raise ValueError(
                f"Beam collapsed at step {k + 1}: no valid states remain. "
                + (
                    "No candidate satisfies the hard-mode constraints — "
                    "was this game really played in hard mode? "
                    if hard_mode else ""
                )
                + "Check that the pattern trace is consistent with the answer."
            )

        new_beam.sort(key=lambda s: -s.log_prob)
        beam = new_beam[:beam_width]

    # -----------------------------------------------------------------------
    # For a won game, append the final deterministic guess (the answer itself).
    # For a lost game, every observed guess is already reconstructed.
    # -----------------------------------------------------------------------
    if won:
        final_beam: list[BeamState] = []
        for state in beam:
            n_before = len(state.remaining_words)
            final_beam.append(BeamState(
                guesses=state.guesses + [answer],
                remaining_words=[answer],
                log_prob=state.log_prob,
                step_probs=state.step_probs + [1.0],
                remaining_sizes=state.remaining_sizes + [(n_before, 1)],
                n_candidates=state.n_candidates + [1],
                top_alternatives_per_step=state.top_alternatives_per_step + [[(answer, 1.0)]],
            ))
        beam = final_beam

    return _format_results(beam, parsed_patterns, won)


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------


def _format_results(
    beam: list[BeamState],
    patterns: list[int],
    won: bool,
) -> list[dict]:
    """Format beam states into ranked reconstruction result dicts."""
    log_probs = np.array([s.log_prob for s in beam])
    # Normalize relative probabilities within the returned top-K
    shifted = log_probs - log_probs.max()
    exp_shifted = np.exp(shifted)
    normalized = exp_shifted / exp_shifted.sum()

    results = []
    for rank, (state, norm_prob) in enumerate(zip(beam, normalized)):
        step_infos = []
        for i, (guess, pattern, step_prob, (n_before, n_after), n_cands, top_alts) in enumerate(
            zip(
                state.guesses,
                patterns,
                state.step_probs,
                state.remaining_sizes,
                state.n_candidates,
                state.top_alternatives_per_step,
            )
        ):
            step_infos.append({
                "step": i + 1,
                "guess": guess,
                "pattern": pattern,
                "pattern_str": pattern_to_string(pattern),
                "n_candidates": n_cands,
                "n_remaining_before": n_before,
                "n_remaining_after": n_after,
                "step_probability": step_prob,
                "top_alternatives": top_alts,
            })

        results.append({
            "rank": rank + 1,
            "guesses": state.guesses,
            "won": won,
            "log_probability": float(state.log_prob),
            "normalized_probability": float(norm_prob),
            "step_info": step_infos,
        })

    return results
