"""Reverse Wordle solver: reconstruct the most likely guess sequence from a pattern trace.

Given the correct answer and the color pattern for each row, this module finds the
most probable sequence of guesses a human player made, using a Boltzmann model of
rationality calibrated against the entropy-based forward solver.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from scipy.special import log_softmax

from src.entropy import get_entropies
from src.pattern import get_pattern_matrix, get_possible_words, pattern_to_string
from src.prior import get_true_wordle_prior, get_word_list
from src.solver import get_weights

logger = logging.getLogger(__name__)

# Rationality presets: higher beta = closer to optimal play
BETA_PRESETS: dict[str, float] = {
    "random": 0.0,
    "casual": 2.0,
    "normal": 5.0,
    "expert": 10.0,
}

# Precomputed forward-solver prior for first guesses.
# Maps word -> log_prior (0.0 = best opener, more negative = worse).
# Generated by precompute_opener_prior.py; covers ~1125 top openers.
# Words not in the dict receive OPENER_PRIOR_DEFAULT (~median of excluded set).
_OPENER_PRIOR_FILE = Path(__file__).parent.parent / "data" / "wordle" / "opener_prior.json"
OPENER_PRIOR: dict[str, float] = {}
OPENER_PRIOR_WEIGHT: float = 10.0   # step 0 (opener selection)
WORD_QUALITY_WEIGHT: float = 3.0    # steps 1+ (familiarity proxy)
OPENER_PRIOR_DEFAULT: float = -0.5  # penalty for words not in the prior dict
POSSIBLE_ANSWER_BONUS: float = 3.5       # nats bonus at n=1 remaining (endgame)
POSSIBLE_ANSWER_BONUS_BASE: float = 1.0  # nats bonus at n>=ANSWER_BONUS_RAMP_N remaining
ANSWER_BONUS_RAMP_N: int = 12            # linearly interpolate between base and full below this

try:
    OPENER_PRIOR = json.loads(_OPENER_PRIOR_FILE.read_text())
except FileNotFoundError:
    logging.getLogger(__name__).warning(
        "opener_prior.json not found — run precompute_opener_prior.py to generate it. "
        "First-guess prior will be flat."
    )

ALL_GREEN_PATTERN: int = 3**5 - 1  # 242

_EMOJI_TO_INT = {"⬛": 0, "⬜": 0, "🟨": 1, "🟩": 2}


# ---------------------------------------------------------------------------
# Pattern parsing
# ---------------------------------------------------------------------------


def parse_pattern(pattern) -> int:
    """Convert a pattern to its integer encoding (0–242).

    Accepts:
    - An int already in range 0–242
    - A 5-element list/tuple of ints in {0, 1, 2}  (MISS=0, MISPLACED=1, EXACT=2)
    - A 5-emoji string using ⬛🟨🟩
    """
    if isinstance(pattern, int):
        if not 0 <= pattern <= 242:
            raise ValueError(f"Pattern int must be 0–242, got {pattern}")
        return pattern
    if isinstance(pattern, str):
        chars = list(pattern)
        if len(chars) != 5 or not all(c in _EMOJI_TO_INT for c in chars):
            raise ValueError(
                f"Pattern string must be 5 emoji from {{⬛,🟨,🟩}}, got '{pattern}'"
            )
        return sum(_EMOJI_TO_INT[c] * (3**i) for i, c in enumerate(chars))
    values = list(pattern)
    if len(values) != 5:
        raise ValueError(f"Pattern list must have length 5, got {len(values)}")
    if not all(v in (0, 1, 2) for v in values):
        raise ValueError(f"Pattern values must be in {{0,1,2}}, got {values}")
    return sum(int(v) * (3**i) for i, v in enumerate(values))


def parse_pattern_trace(patterns: list) -> list[int]:
    """Normalize a full trace; validate that the last pattern is all-green (242)."""
    parsed = [parse_pattern(p) for p in patterns]
    if not parsed:
        raise ValueError("Pattern trace must be non-empty")
    if parsed[-1] != ALL_GREEN_PATTERN:
        raise ValueError(
            f"Last pattern must be all-green ({ALL_GREEN_PATTERN}), got {parsed[-1]}. "
            "The reverse solver assumes the player succeeded on the final guess."
        )
    return parsed


# ---------------------------------------------------------------------------
# Candidate lookup
# ---------------------------------------------------------------------------


def get_candidates_for_pattern(
    answer: str,
    pattern: int,
    allowed_words: list[str],
    game_name: str,
) -> list[str]:
    """Return every word in allowed_words that produces `pattern` against `answer`."""
    col = get_pattern_matrix(allowed_words, [answer], game_name).flatten()
    return [w for w, p in zip(allowed_words, col) if p == pattern]


# ---------------------------------------------------------------------------
# Beam search state
# ---------------------------------------------------------------------------


@dataclass
class BeamState:
    guesses: list[str] = field(default_factory=list)
    remaining_words: list[str] = field(default_factory=list)
    log_prob: float = 0.0
    step_probs: list[float] = field(default_factory=list)
    # (n_remaining_before, n_remaining_after) at each step
    remaining_sizes: list[tuple[int, int]] = field(default_factory=list)
    # top alternatives (word, prob) at each step
    top_alternatives_per_step: list[list[tuple[str, float]]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Scoring
# ---------------------------------------------------------------------------


def _score_candidates(
    candidates: list[str],
    remaining_words: list[str],
    priors: dict[str, float],
    beta: float,
    game_name: str,
    step: int,
) -> np.ndarray:
    """Return log-probabilities for the human choosing each candidate.

    Model: P(G | state) ∝ exp(β · H(G)), where H(G) is the Shannon entropy
    gained by guessing G given the current remaining word distribution.
    At step 0, an additive prior from the forward solver's expected scores is
    applied: better openers (lower expected total guesses) receive higher prior.
    """
    if not candidates or not remaining_words:
        return np.full(len(candidates), -np.inf)

    weights = get_weights(remaining_words, priors)
    entropies = get_entropies(candidates, remaining_words, weights, game_name)

    scores = beta * entropies

    # Possible-answer bonus: linearly ramps from POSSIBLE_ANSWER_BONUS (at n=1)
    # down to POSSIBLE_ANSWER_BONUS_BASE (at n>=ANSWER_BONUS_RAMP_N).
    # Models (a) lucky-win probability and (b) human preference for real words.
    remaining_set = set(remaining_words)
    t = max(0.0, min(1.0, (ANSWER_BONUS_RAMP_N - len(remaining_words)) / (ANSWER_BONUS_RAMP_N - 1)))
    answer_bonus = POSSIBLE_ANSWER_BONUS_BASE + (POSSIBLE_ANSWER_BONUS - POSSIBLE_ANSWER_BONUS_BASE) * t
    scores += answer_bonus * np.array(
        [1.0 if c in remaining_set else 0.0 for c in candidates]
    )

    if OPENER_PRIOR:
        # Apply word-quality prior at every step: better openers (via forward solver)
        # serve as a proxy for word familiarity. Weight is higher at step 0, where
        # humans rely most on prior knowledge, and lower thereafter.
        # Words absent from the dict (non-answer fallback words) get a penalty so they
        # are strongly disfavoured over familiar answer-list words.
        weight = OPENER_PRIOR_WEIGHT if step == 0 else WORD_QUALITY_WEIGHT
        scores += weight * np.array(
            [OPENER_PRIOR.get(c, OPENER_PRIOR_DEFAULT) for c in candidates]
        )

    return log_softmax(scores)


# ---------------------------------------------------------------------------
# Main reconstruction function
# ---------------------------------------------------------------------------


def reconstruct_guesses(
    patterns: list,
    answer: str,
    game_name: str = "wordle",
    beta: float = 5.0,
    beam_width: int = 200,
    expansion_per_state: int = 20,
    priors: dict[str, float] | None = None,
    n_top_alternatives: int = 5,
    hard_mode: bool = False,
    restrict_to_answers: bool = False,
) -> list[dict]:
    """Reconstruct the most likely sequence of Wordle guesses from a pattern trace.

    Args:
        patterns: List of N patterns. Each can be an int (0–242), a 5-int list, or
                  a 5-emoji string. The last pattern MUST be all-green (the win).
        answer:   The correct answer word.
        game_name: "wordle" or "dungleon".
        beta:     Rationality parameter. Use BETA_PRESETS or pass a float directly.
                  0 = random play, 5 = normal human, 10 = near-optimal.
        beam_width: States kept after pruning at each step. Larger values improve the
                    probability denominator estimate and yield more merge candidates.
                    Default 200.
        expansion_per_state: Candidates expanded per beam state per step. Controls
                    compute cost independently of beam_width. Default 20.
        priors:   Word probability dict. Defaults to frequency-based priors.
        n_top_alternatives: Alternatives to report per step in output.
        hard_mode: If True, candidates at step k must also be in current remaining_words
                   (Wordle hard mode constraint).
        restrict_to_answers: If False (default), try answer words first and fall back to
                             the full 12,972-word list only when no answer word matches
                             the observed pattern. If True, never use non-answer words
                             (will raise ValueError if a non-answer word is required).

    Returns:
        List of result dicts ranked by probability. Each dict contains:
          rank, guesses, log_probability, normalized_probability, step_info.
        step_info is a list of per-step dicts with guess, pattern, pattern_str,
        n_candidates, n_remaining_before, n_remaining_after, step_probability,
        top_alternatives.
    """
    parsed_patterns = parse_pattern_trace(patterns)
    n_guesses = len(parsed_patterns)

    if priors is None:
        priors = get_true_wordle_prior(game_name)

    allowed_words = get_word_list(game_name, short=False)
    possible_words = get_word_list(game_name, short=True)

    allowed_set = set(allowed_words)
    if answer not in allowed_set:
        raise ValueError(f"Answer '{answer}' not in allowed words for game '{game_name}'")

    # Initial remaining: possible answers with nonzero prior (matches forward solver)
    initial_remaining = [w for w in possible_words if priors.get(w, 0) > 0]

    # Precompute candidates for steps 0..N-2 (last step is always the answer, pattern 242).
    # Use answer-list words first; fall back to full allowed list only when no answer word
    # produces the observed pattern — this matches HTML behaviour and avoids surfacing
    # obscure-but-valid words (e.g. REALO, FUBAR) unless the player actually typed one.
    step_candidates: list[list[str]] = []
    for k in range(n_guesses - 1):
        candidates = get_candidates_for_pattern(
            answer, parsed_patterns[k], possible_words, game_name
        )
        if not candidates and not restrict_to_answers:
            candidates = get_candidates_for_pattern(
                answer, parsed_patterns[k], allowed_words, game_name
            )
        if not candidates:
            raise ValueError(
                f"No {'answer-list' if restrict_to_answers else 'allowed'} word produces "
                f"pattern {parsed_patterns[k]} ({pattern_to_string(parsed_patterns[k])}) "
                f"against answer '{answer}' at step {k + 1}. "
                "The trace may be inconsistent with the answer."
            )
        logger.debug(
            "Step %d: %d candidates for %s",
            k + 1, len(candidates), pattern_to_string(parsed_patterns[k]),
        )
        step_candidates.append(candidates)

    n_candidates_per_step = [len(c) for c in step_candidates] + [1]

    # Initialize beam with a single state covering all possible answers
    beam: list[BeamState] = [
        BeamState(
            guesses=[],
            remaining_words=initial_remaining,
            log_prob=0.0,
            step_probs=[],
            remaining_sizes=[],
            top_alternatives_per_step=[],
        )
    ]

    # -----------------------------------------------------------------------
    # Beam search over steps 0..N-2
    # -----------------------------------------------------------------------
    for k in range(n_guesses - 1):
        all_candidates = step_candidates[k]
        p_k = parsed_patterns[k]
        new_beam: list[BeamState] = []

        for state in beam:
            if not state.remaining_words:
                continue

            # In hard mode, restrict candidates to those still in remaining_words
            candidates = (
                [c for c in all_candidates if c in set(state.remaining_words)]
                if hard_mode
                else all_candidates
            )
            if not candidates:
                continue

            log_probs = _score_candidates(
                candidates,
                state.remaining_words,
                priors,
                beta,
                game_name,
                step=k,
            )

            # Top alternatives for output (before expansion pruning)
            top_alt_idx = np.argsort(log_probs)[-n_top_alternatives:][::-1]
            top_alts = [
                (candidates[i], float(np.exp(log_probs[i]))) for i in top_alt_idx
            ]

            # Expand top candidates per state; keep beam_width separate from expansion
            # so the stored beam is large (good denominator) without quadratic blowup.
            expansion_limit = min(expansion_per_state, len(candidates))
            expand_idx = np.argsort(log_probs)[-expansion_limit:]

            n_before = len(state.remaining_words)
            for i in expand_idx:
                guess = candidates[i]
                lp = float(log_probs[i])
                new_remaining = get_possible_words(
                    guess, p_k, state.remaining_words, game_name
                )
                new_beam.append(BeamState(
                    guesses=state.guesses + [guess],
                    remaining_words=new_remaining,
                    log_prob=state.log_prob + lp,
                    step_probs=state.step_probs + [float(np.exp(lp))],
                    remaining_sizes=state.remaining_sizes + [(n_before, len(new_remaining))],
                    top_alternatives_per_step=state.top_alternatives_per_step + [top_alts],
                ))

        if not new_beam:
            raise ValueError(
                f"Beam collapsed at step {k + 1}: no valid states remain. "
                "Check that the pattern trace is consistent with the answer."
            )

        new_beam.sort(key=lambda s: -s.log_prob)
        beam = new_beam[:beam_width]

    # -----------------------------------------------------------------------
    # Append the final deterministic guess (the answer itself)
    # -----------------------------------------------------------------------
    final_beam: list[BeamState] = []
    for state in beam:
        n_before = len(state.remaining_words)
        final_beam.append(BeamState(
            guesses=state.guesses + [answer],
            remaining_words=[answer],
            log_prob=state.log_prob,
            step_probs=state.step_probs + [1.0],
            remaining_sizes=state.remaining_sizes + [(n_before, 1)],
            top_alternatives_per_step=state.top_alternatives_per_step + [[(answer, 1.0)]],
        ))

    return _format_results(final_beam, parsed_patterns, n_candidates_per_step, answer)


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------


def _format_results(
    beam: list[BeamState],
    patterns: list[int],
    n_candidates_per_step: list[int],
    answer: str,
) -> list[dict]:
    """Format beam states into ranked reconstruction result dicts."""
    log_probs = np.array([s.log_prob for s in beam])
    # Normalize relative probabilities within the returned top-K
    shifted = log_probs - log_probs.max()
    exp_shifted = np.exp(shifted)
    normalized = exp_shifted / exp_shifted.sum()

    results = []
    for rank, (state, norm_prob) in enumerate(zip(beam, normalized)):
        step_infos = []
        for i, (guess, pattern, step_prob, (n_before, n_after), top_alts) in enumerate(
            zip(
                state.guesses,
                patterns,
                state.step_probs,
                state.remaining_sizes,
                state.top_alternatives_per_step,
            )
        ):
            step_infos.append({
                "step": i + 1,
                "guess": guess,
                "pattern": pattern,
                "pattern_str": pattern_to_string(pattern),
                "n_candidates": n_candidates_per_step[i],
                "n_remaining_before": n_before,
                "n_remaining_after": n_after,
                "step_probability": step_prob,
                "top_alternatives": top_alts,
            })

        results.append({
            "rank": rank + 1,
            "guesses": state.guesses,
            "log_probability": float(state.log_prob),
            "normalized_probability": float(norm_prob),
            "step_info": step_infos,
        })

    return results
